apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      serviceAccountName: todo
      containers:
        - name: todo
          image: <account-id>.dkr.ecr.<region>.amazonaws.com/todo-dev
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
